# site settings
title: Nexus of Homelessness
subtitle: by Austin Moon
email: travisching007@gmail.com
description: An exploration of my journey examining and bringing to light the experiences and problems the homeless face in the darkness to the general public.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/AustinM_Nexus

# build settings
markdown: kramdown

sass:
  style: compressed
